import { D, type GameValue } from "@/utils/decimal";
import { canAfford, ECONOMY } from "./economy";

interface FactoryProductionValueInput {
  /** Multiplier granted by invoked gods and applied to factory production. */
  godsProductionMultiplier: GameValue;
  /** Whether this factory has purchased its production upgrade. */
  isUpgraded: boolean;
  /** Base gold generated by one unit before multipliers are applied. */
  productionValue: number;
}

interface FactoryEarnInput extends FactoryProductionValueInput {
  /** Number of owned units contributing to the production cycle. */
  amount: number;
}

/**
 * Calculates the production value of a single factory unit after upgrades and
 * global god multipliers are applied.
 *
 * @example
 * getFactoryProductionValue({ productionValue: 20, isUpgraded: false, godsProductionMultiplier: D(3) }).toNumber() // 60
 * getFactoryProductionValue({ productionValue: 20, isUpgraded: true, godsProductionMultiplier: D(3) }).toNumber() // 120
 */
export const getFactoryProductionValue = ({
  godsProductionMultiplier,
  isUpgraded,
  productionValue,
}: FactoryProductionValueInput): GameValue =>
  D(productionValue)
    .times(isUpgraded ? ECONOMY.upgradeProductionMultiplier : 1)
    .times(godsProductionMultiplier);

/**
 * Calculates how much gold a factory earns when one production cycle finishes.
 *
 * @example
 * getFactoryEarnPerCycle({ amount: 3, productionValue: 10, isUpgraded: false, godsProductionMultiplier: D(1) }).toNumber() // 30
 */
export const getFactoryEarnPerCycle = (input: FactoryEarnInput): GameValue =>
  getFactoryProductionValue(input).times(input.amount);

const SECONDS_PER_HOUR = 3600;

interface FactoryProductionState {
  isAutomated: boolean;
  isProducing: boolean;
  isUnlocked: boolean;
}

interface ManualProductionState extends FactoryProductionState {
  isProducing: boolean;
}

interface ManagerPurchaseState {
  cost: GameValue;
  gold: GameValue;
  isAutomated: boolean;
  isUnlocked: boolean;
}

interface UpgradePurchaseState {
  cost: GameValue;
  gold: GameValue;
  isUnlocked: boolean;
  isUpgraded: boolean;
}

/**
 * Calculates hourly yield from per-cycle yield and cycle duration.
 *
 * @example
 * getFactoryYieldPerHour(D(10), 10).toNumber() // 3600
 */
export const getFactoryYieldPerHour = (
  yieldPerCycle: GameValue,
  productionTime: number
): GameValue => yieldPerCycle.times(SECONDS_PER_HOUR).div(productionTime);

/**
 * Display label for the production upgrade multiplier.
 *
 * @example
 * getUpgradeMultiplierLabel() // "2x"
 */
export const getUpgradeMultiplierLabel = (): string =>
  `${ECONOMY.upgradeProductionMultiplier}x`;

/**
 * Whether a factory should be driven by the production scheduler.
 *
 * @example
 * isFactoryProductionActive({ isUnlocked: true, isAutomated: true, isProducing: false }) // true
 * isFactoryProductionActive({ isUnlocked: false, isAutomated: true, isProducing: false }) // false
 */
export const isFactoryProductionActive = ({
  isAutomated,
  isProducing,
  isUnlocked,
}: FactoryProductionState): boolean =>
  isUnlocked && (isAutomated || isProducing);

/**
 * Whether the player can start a manual production tap.
 *
 * @example
 * canStartManualProduction({ isUnlocked: true, isAutomated: false, isProducing: false }) // true
 * canStartManualProduction({ isUnlocked: true, isAutomated: true, isProducing: false }) // false
 */
export const canStartManualProduction = ({
  isAutomated,
  isProducing,
  isUnlocked,
}: ManualProductionState): boolean =>
  isUnlocked && !isAutomated && !isProducing;

/**
 * Whether the player can appoint a manager for this factory.
 *
 * @example
 * canPurchaseManager({ isUnlocked: true, isAutomated: false, gold: D(100), cost: D(50) }) // true
 * canPurchaseManager({ isUnlocked: true, isAutomated: true, gold: D(100), cost: D(50) }) // false
 */
export const canPurchaseManager = ({
  cost,
  gold,
  isAutomated,
  isUnlocked,
}: ManagerPurchaseState): boolean =>
  isUnlocked && !isAutomated && canAfford(gold, cost);

/**
 * Whether the player can purchase the production upgrade.
 *
 * @example
 * canPurchaseUpgrade({ isUnlocked: true, isUpgraded: false, gold: D(100), cost: D(50) }) // true
 * canPurchaseUpgrade({ isUnlocked: true, isUpgraded: true, gold: D(100), cost: D(50) }) // false
 */
export const canPurchaseUpgrade = ({
  cost,
  gold,
  isUnlocked,
  isUpgraded,
}: UpgradePurchaseState): boolean =>
  isUnlocked && !isUpgraded && canAfford(gold, cost);
