import { D, type GameValue } from "@/utils/decimal";
import { ECONOMY } from "./economy";

interface FactoryProductionValueInput {
  /** Multiplier granted by invoked gods and applied to factory production. */
  godsProductionMultiplier: GameValue;
  /** Whether this factory has purchased its production upgrade. */
  isUpgraded: boolean;
  /** Base gold generated by one unit before multipliers are applied. */
  productionValue: number;
}

interface FactoryEarnInput extends FactoryProductionValueInput {
  /** Number of owned units contributing to the production cycle. */
  amount: number;
}

/**
 * Calculates the production value of a single factory unit after upgrades and
 * global god multipliers are applied.
 */
export const getFactoryProductionValue = ({
  godsProductionMultiplier,
  isUpgraded,
  productionValue,
}: FactoryProductionValueInput): GameValue =>
  D(productionValue)
    .times(isUpgraded ? ECONOMY.upgradeProductionMultiplier : 1)
    .times(godsProductionMultiplier);

/**
 * Calculates how much gold a factory earns when one production cycle finishes.
 */
export const getFactoryEarnPerCycle = (input: FactoryEarnInput): GameValue =>
  getFactoryProductionValue(input).times(input.amount);
