import type { MissionDefinition } from "./types";

export const MISSION_DATA = [
  {
    id: "mission-001",
    order: 1,
    objective: {
      type: "ownUnits",
      factory: "grain",
      target: 1,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "250" }],
  },
  {
    id: "mission-002",
    order: 2,
    objective: {
      type: "completeCycles",
      target: 8,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "500" }],
  },
  {
    id: "mission-003",
    order: 3,
    objective: {
      type: "earnGold",
      target: "1500",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "750" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "common" },
    ],
  },
  {
    id: "mission-004",
    order: 4,
    objective: {
      type: "ownUnits",
      factory: "grain",
      target: 4,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "1000" }],
  },
  {
    id: "mission-005",
    order: 5,
    objective: {
      type: "earnGold",
      target: "4000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "1250" }],
  },
  {
    id: "mission-006",
    order: 6,
    objective: {
      type: "upgradeFactory",
      factory: "grain",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "1500" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "common" },
    ],
  },
  {
    id: "mission-007",
    order: 7,
    objective: {
      type: "completeCycles",
      target: 20,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "1750" }],
  },
  {
    id: "mission-008",
    order: 8,
    objective: {
      type: "earnGold",
      target: "8000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "2000" },
      { type: "renown", percent: 0.5 },
    ],
  },
  {
    id: "mission-009",
    order: 9,
    objective: {
      type: "ownUnits",
      factory: "grain",
      target: 8,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "2250" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "common" },
    ],
  },
  {
    id: "mission-010",
    order: 10,
    objective: {
      type: "spendGold",
      target: "6000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "2500" }],
  },
  {
    id: "mission-011",
    order: 11,
    objective: {
      type: "automateFactory",
      factory: "grain",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "2750" }],
  },
  {
    id: "mission-012",
    order: 12,
    objective: {
      type: "holdGold",
      target: "12000",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "3000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "common" },
    ],
  },
  {
    id: "mission-013",
    order: 13,
    objective: {
      type: "ownUnits",
      factory: "grain",
      target: 12,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "3250" }],
  },
  {
    id: "mission-014",
    order: 14,
    objective: {
      type: "earnGold",
      target: "20000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "3500" }],
  },
  {
    id: "mission-015",
    order: 15,
    objective: {
      type: "claimDailyRewards",
      target: 1,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "3750" }],
  },
  {
    id: "mission-016",
    order: 16,
    objective: {
      type: "completeCycles",
      target: 35,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "4000" }],
  },
  {
    id: "mission-017",
    order: 17,
    objective: {
      type: "activatePowerUps",
      target: 1,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "4250" }],
  },
  {
    id: "mission-018",
    order: 18,
    objective: {
      type: "spendGold",
      target: "40000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "4500" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "uncommon" },
    ],
  },
  {
    id: "mission-019",
    order: 19,
    objective: {
      type: "ownUnits",
      factory: "grain",
      target: 18,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "4750" }],
  },
  {
    id: "mission-020",
    order: 20,
    objective: {
      type: "unlockFactory",
      factory: "wine",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "5000" },
      { type: "renown", percent: 0.5 },
    ],
  },
  {
    id: "mission-021",
    order: 21,
    requires: { minFactoryUnlocked: "wine" },
    objective: {
      type: "earnGold",
      target: "165000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "15000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "uncommon" },
    ],
  },
  {
    id: "mission-022",
    order: 22,
    requires: { minFactoryUnlocked: "wine" },
    objective: {
      type: "ownUnits",
      factory: "wine",
      target: 4,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "18000" }],
  },
  {
    id: "mission-023",
    order: 23,
    requires: { minFactoryUnlocked: "wine" },
    objective: {
      type: "completeCycles",
      target: 45,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "20000" }],
  },
  {
    id: "mission-024",
    order: 24,
    requires: { minFactoryUnlocked: "wine" },
    objective: {
      type: "spendGold",
      target: "120000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "22000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "uncommon" },
    ],
  },
  {
    id: "mission-025",
    order: 25,
    requires: { minFactoryUnlocked: "wine" },
    objective: {
      type: "earnGold",
      target: "280000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "25000" },
      { type: "renown", percent: 0.75 },
    ],
  },
  {
    id: "mission-026",
    order: 26,
    requires: { minFactoryUnlocked: "wine" },
    objective: {
      type: "ownUnits",
      factory: "wine",
      target: 8,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "28000" }],
  },
  {
    id: "mission-027",
    order: 27,
    requires: { minFactoryUnlocked: "wine" },
    objective: {
      type: "upgradeFactory",
      factory: "wine",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "30000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "uncommon" },
    ],
  },
  {
    id: "mission-028",
    order: 28,
    requires: { minFactoryUnlocked: "wine" },
    objective: {
      type: "automateFactory",
      factory: "wine",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "32000" }],
  },
  {
    id: "mission-029",
    order: 29,
    requires: { minFactoryUnlocked: "wine" },
    objective: {
      type: "unlockFactory",
      factory: "iron",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "35000" }],
  },
  {
    id: "mission-030",
    order: 30,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "ownUnits",
      factory: "iron",
      target: 4,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "40000" }],
  },
  {
    id: "mission-031",
    order: 31,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "earnGold",
      target: "600000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "45000" }],
  },
  {
    id: "mission-032",
    order: 32,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "completeCycles",
      target: 70,
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "50000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "uncommon" },
    ],
  },
  {
    id: "mission-033",
    order: 33,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "upgradeFactory",
      factory: "iron",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "55000" }],
  },
  {
    id: "mission-034",
    order: 34,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "automateFactory",
      factory: "iron",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "60000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "uncommon" },
    ],
  },
  {
    id: "mission-035",
    order: 35,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "ownUnits",
      factory: "iron",
      target: 10,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "65000" },
      { type: "renown", percent: 0.75 },
    ],
  },
  {
    id: "mission-036",
    order: 36,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "earnGold",
      target: "1200000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "70000" }],
  },
  {
    id: "mission-037",
    order: 37,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "spendGold",
      target: "800000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "75000" }],
  },
  {
    id: "mission-038",
    order: 38,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "ownUnits",
      factory: "iron",
      target: 14,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "80000" }],
  },
  {
    id: "mission-039",
    order: 39,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "claimDailyRewards",
      target: 2,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "85000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "rare" },
    ],
  },
  {
    id: "mission-040",
    order: 40,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "activatePowerUps",
      target: 2,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "90000" }],
  },
  {
    id: "mission-041",
    order: 41,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "earnGold",
      target: "2500000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "95000" }],
  },
  {
    id: "mission-042",
    order: 42,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "holdGold",
      target: "600000",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "100000" },
      { type: "renown", percent: 0.75 },
    ],
  },
  {
    id: "mission-043",
    order: 43,
    requires: { minFactoryUnlocked: "iron" },
    objective: {
      type: "unlockFactory",
      factory: "crossbow",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "120000" }],
  },
  {
    id: "mission-044",
    order: 44,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 4,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "150000" }],
  },
  {
    id: "mission-045",
    order: 45,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "earnGold",
      target: "8000000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "180000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "rare" },
    ],
  },
  {
    id: "mission-046",
    order: 46,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "completeCycles",
      target: 110,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "200000" }],
  },
  {
    id: "mission-047",
    order: 47,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "holdGold",
      target: "8000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "220000" }],
  },
  {
    id: "mission-048",
    order: 48,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 6,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "250000" }],
  },
  {
    id: "mission-049",
    order: 49,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "activatePowerUps",
      target: 3,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "280000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "rare" },
    ],
  },
  {
    id: "mission-050",
    order: 50,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "earnGold",
      target: "15000000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "300000" },
      { type: "renown", percent: 1 },
    ],
  },
  {
    id: "mission-051",
    order: 51,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "spendGold",
      target: "10000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "350000" }],
  },
  {
    id: "mission-052",
    order: 52,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 10,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "400000" }],
  },
  {
    id: "mission-053",
    order: 53,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "upgradeFactory",
      factory: "crossbow",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "450000" }],
  },
  {
    id: "mission-054",
    order: 54,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "automateFactory",
      factory: "crossbow",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "500000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "rare" },
    ],
  },
  {
    id: "mission-055",
    order: 55,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "earnGold",
      target: "50000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "600000" }],
  },
  {
    id: "mission-056",
    order: 56,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "holdGold",
      target: "100000000",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "700000" },
      { type: "renown", percent: 1 },
    ],
  },
  {
    id: "mission-057",
    order: 57,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "completeCycles",
      target: 160,
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "800000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "rare" },
    ],
  },
  {
    id: "mission-058",
    order: 58,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "claimDailyRewards",
      target: 3,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "900000" }],
  },
  {
    id: "mission-059",
    order: 59,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "unlockFactory",
      factory: "longship",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "1000000" }],
  },
  {
    id: "mission-060",
    order: 60,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "earnGold",
      target: "150000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "1200000" }],
  },
  {
    id: "mission-061",
    order: 61,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 12,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "1400000" }],
  },
  {
    id: "mission-062",
    order: 62,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "earnGold",
      target: "300000000",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "1600000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "rare" },
    ],
  },
  {
    id: "mission-063",
    order: 63,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 4,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "1800000" },
      { type: "renown", percent: 1 },
    ],
  },
  {
    id: "mission-064",
    order: 64,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "holdGold",
      target: "400000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "2000000" }],
  },
  {
    id: "mission-065",
    order: 65,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "earnGold",
      target: "500000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "2200000" }],
  },
  {
    id: "mission-066",
    order: 66,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "spendGold",
      target: "200000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "2400000" }],
  },
  {
    id: "mission-067",
    order: 67,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "completeCycles",
      target: 200,
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "2600000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "epic" },
    ],
  },
  {
    id: "mission-068",
    order: 68,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "activatePowerUps",
      target: 4,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "2800000" }],
  },
  {
    id: "mission-069",
    order: 69,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "upgradeFactory",
      factory: "longship",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "3000000" },
      { type: "renown", percent: 1 },
    ],
  },
  {
    id: "mission-070",
    order: 70,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "holdGold",
      target: "750000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "3500000" }],
  },
  {
    id: "mission-071",
    order: 71,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "earnGold",
      target: "1000000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "4000000" }],
  },
  {
    id: "mission-072",
    order: 72,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "spendGold",
      target: "800000000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "4500000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "epic" },
    ],
  },
  {
    id: "mission-073",
    order: 73,
    requires: { minFactoryUnlocked: "crossbow" },
    objective: {
      type: "earnGold",
      target: "1200000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "5000000" }],
  },
  {
    id: "mission-074",
    order: 74,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 6,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "6000000" }],
  },
  {
    id: "mission-075",
    order: 75,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "earnGold",
      target: "1500000000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "7000000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "epic" },
    ],
  },
  {
    id: "mission-076",
    order: 76,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "automateFactory",
      factory: "longship",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "8000000" },
      { type: "renown", percent: 1.5 },
    ],
  },
  {
    id: "mission-077",
    order: 77,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "holdGold",
      target: "2000000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "9000000" }],
  },
  {
    id: "mission-078",
    order: 78,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 8,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "10000000" }],
  },
  {
    id: "mission-079",
    order: 79,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "completeCycles",
      target: 250,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "11000000" }],
  },
  {
    id: "mission-080",
    order: 80,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "earnGold",
      target: "3000000000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "12000000" },
      { type: "renown", percent: 1.5 },
    ],
  },
  {
    id: "mission-081",
    order: 81,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "upgradeFactory",
      factory: "longship",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "13000000" }],
  },
  {
    id: "mission-082",
    order: 82,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "automateFactory",
      factory: "longship",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "14000000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "epic" },
    ],
  },
  {
    id: "mission-083",
    order: 83,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "holdGold",
      target: "5000000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "15000000" }],
  },
  {
    id: "mission-084",
    order: 84,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 12,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "16000000" }],
  },
  {
    id: "mission-085",
    order: 85,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "earnGold",
      target: "3000000000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "18000000" },
      { type: "renown", percent: 1.5 },
    ],
  },
  {
    id: "mission-086",
    order: 86,
    requires: { minFactoryUnlocked: "longship" },
    objective: {
      type: "unlockFactory",
      factory: "reliquary",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "20000000" }],
  },
  {
    id: "mission-087",
    order: 87,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 4,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "22000000" }],
  },
  {
    id: "mission-088",
    order: 88,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "8000000000",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "24000000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "epic" },
    ],
  },
  {
    id: "mission-089",
    order: 89,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "12000000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "26000000" }],
  },
  {
    id: "mission-090",
    order: 90,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "10000000000",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "28000000" },
      { type: "renown", percent: 2 },
    ],
  },
  {
    id: "mission-091",
    order: 91,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 10,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "30000000" }],
  },
  {
    id: "mission-092",
    order: 92,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "completeCycles",
      target: 300,
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "32000000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "epic" },
    ],
  },
  {
    id: "mission-093",
    order: 93,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "20000000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "34000000" }],
  },
  {
    id: "mission-094",
    order: 94,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "25000000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "36000000" }],
  },
  {
    id: "mission-095",
    order: 95,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "activatePowerUps",
      target: 5,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "38000000" },
      { type: "renown", percent: 2 },
    ],
  },
  {
    id: "mission-096",
    order: 96,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 16,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "40000000" }],
  },
  {
    id: "mission-097",
    order: 97,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "spendGold",
      target: "30000000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "42000000" }],
  },
  {
    id: "mission-098",
    order: 98,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "40000000000",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "44000000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "epic" },
    ],
  },
  {
    id: "mission-099",
    order: 99,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "50000000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "46000000" }],
  },
  {
    id: "mission-100",
    order: 100,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 25,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "50000000" },
      { type: "renown", percent: 2 },
    ],
  },
  {
    id: "mission-101",
    order: 101,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "upgradeFactory",
      factory: "reliquary",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "100500000" }],
  },
  {
    id: "mission-102",
    order: 102,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "55000000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "101000000" }],
  },
  {
    id: "mission-103",
    order: 103,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "62100000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "101500000" }],
  },
  {
    id: "mission-104",
    order: 104,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "completeCycles",
      target: 344,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "102000000" }],
  },
  {
    id: "mission-105",
    order: 105,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 14,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "102500000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "epic" },
    ],
  },
  {
    id: "mission-106",
    order: 106,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "spendGold",
      target: "70200000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "103000000" }],
  },
  {
    id: "mission-107",
    order: 107,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "claimDailyRewards",
      target: 4,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "103500000" }],
  },
  {
    id: "mission-108",
    order: 108,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "automateFactory",
      factory: "reliquary",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "104000000" }],
  },
  {
    id: "mission-109",
    order: 109,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 14,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "104500000" }],
  },
  {
    id: "mission-110",
    order: 110,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "79400000000",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "105000000" },
      { type: "renown", percent: 2 },
    ],
  },
  {
    id: "mission-111",
    order: 111,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 28,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "105500000" }],
  },
  {
    id: "mission-112",
    order: 112,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "89700000000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "106000000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "epic" },
    ],
  },
  {
    id: "mission-113",
    order: 113,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "upgradeFactory",
      factory: "longship",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "106500000" }],
  },
  {
    id: "mission-114",
    order: 114,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "automateFactory",
      factory: "longship",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "107000000" }],
  },
  {
    id: "mission-115",
    order: 115,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 16,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "107500000" }],
  },
  {
    id: "mission-116",
    order: 116,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "spendGold",
      target: "101300000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "108000000" }],
  },
  {
    id: "mission-117",
    order: 117,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "claimDailyRewards",
      target: 5,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "108500000" }],
  },
  {
    id: "mission-118",
    order: 118,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "activatePowerUps",
      target: 6,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "109000000" }],
  },
  {
    id: "mission-119",
    order: 119,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 15,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "109500000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "epic" },
    ],
  },
  {
    id: "mission-120",
    order: 120,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "114500000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "110000000" }],
  },
  {
    id: "mission-121",
    order: 121,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 30,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "110500000" }],
  },
  {
    id: "mission-122",
    order: 122,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "129400000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "111000000" }],
  },
  {
    id: "mission-123",
    order: 123,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "146200000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "111500000" }],
  },
  {
    id: "mission-124",
    order: 124,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "completeCycles",
      target: 356,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "112000000" }],
  },
  {
    id: "mission-125",
    order: 125,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 18,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "112500000" },
      { type: "renown", percent: 2 },
    ],
  },
  {
    id: "mission-126",
    order: 126,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "spendGold",
      target: "165200000000",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "113000000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "epic" },
    ],
  },
  {
    id: "mission-127",
    order: 127,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "claimDailyRewards",
      target: 6,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "113500000" }],
  },
  {
    id: "mission-128",
    order: 128,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "activatePowerUps",
      target: 7,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "114000000" }],
  },
  {
    id: "mission-129",
    order: 129,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 16,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "114500000" }],
  },
  {
    id: "mission-130",
    order: 130,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "186700000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "115000000" }],
  },
  {
    id: "mission-131",
    order: 131,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 32,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "115500000" }],
  },
  {
    id: "mission-132",
    order: 132,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "211000000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "116000000" }],
  },
  {
    id: "mission-133",
    order: 133,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "238400000000",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "116500000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "epic" },
    ],
  },
  {
    id: "mission-134",
    order: 134,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "completeCycles",
      target: 368,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "117000000" }],
  },
  {
    id: "mission-135",
    order: 135,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 20,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "117500000" }],
  },
  {
    id: "mission-136",
    order: 136,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "spendGold",
      target: "269400000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "118000000" }],
  },
  {
    id: "mission-137",
    order: 137,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "claimDailyRewards",
      target: 7,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "118500000" }],
  },
  {
    id: "mission-138",
    order: 138,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "activatePowerUps",
      target: 8,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "119000000" }],
  },
  {
    id: "mission-139",
    order: 139,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 17,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "119500000" }],
  },
  {
    id: "mission-140",
    order: 140,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "304400000000",
      scope: "run",
    },
    rewards: [
      { type: "gold", amount: "120000000" },
      { type: "renown", percent: 2 },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "epic" },
    ],
  },
  {
    id: "mission-141",
    order: 141,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 34,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "120500000" }],
  },
  {
    id: "mission-142",
    order: 142,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "344000000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "121000000" }],
  },
  {
    id: "mission-143",
    order: 143,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "388700000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "121500000" }],
  },
  {
    id: "mission-144",
    order: 144,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "completeCycles",
      target: 380,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "122000000" }],
  },
  {
    id: "mission-145",
    order: 145,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 22,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "122500000" }],
  },
  {
    id: "mission-146",
    order: 146,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "spendGold",
      target: "439200000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "123000000" }],
  },
  {
    id: "mission-147",
    order: 147,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "claimDailyRewards",
      target: 8,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "123500000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "epic" },
    ],
  },
  {
    id: "mission-148",
    order: 148,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "activatePowerUps",
      target: 9,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "124000000" }],
  },
  {
    id: "mission-149",
    order: 149,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 18,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "124500000" }],
  },
  {
    id: "mission-150",
    order: 150,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "496300000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "125000000" }],
  },
  {
    id: "mission-151",
    order: 151,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 36,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "125500000" }],
  },
  {
    id: "mission-152",
    order: 152,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "560900000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "126000000" }],
  },
  {
    id: "mission-153",
    order: 153,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "633800000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "126500000" }],
  },
  {
    id: "mission-154",
    order: 154,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "completeCycles",
      target: 392,
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "127000000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "epic" },
    ],
  },
  {
    id: "mission-155",
    order: 155,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 24,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "127500000" },
      { type: "renown", percent: 2 },
    ],
  },
  {
    id: "mission-156",
    order: 156,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "spendGold",
      target: "716200000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "128000000" }],
  },
  {
    id: "mission-157",
    order: 157,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "claimDailyRewards",
      target: 9,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "128500000" }],
  },
  {
    id: "mission-158",
    order: 158,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "activatePowerUps",
      target: 10,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "129000000" }],
  },
  {
    id: "mission-159",
    order: 159,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 19,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "129500000" }],
  },
  {
    id: "mission-160",
    order: 160,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "809300000000",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "130000000" }],
  },
  {
    id: "mission-161",
    order: 161,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 38,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "130500000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "epic" },
    ],
  },
  {
    id: "mission-162",
    order: 162,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "914500000000",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "131000000" }],
  },
  {
    id: "mission-163",
    order: 163,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "1e12",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "131500000" }],
  },
  {
    id: "mission-164",
    order: 164,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "completeCycles",
      target: 404,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "132000000" }],
  },
  {
    id: "mission-165",
    order: 165,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 26,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "132500000" }],
  },
  {
    id: "mission-166",
    order: 166,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "spendGold",
      target: "1.2e12",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "133000000" }],
  },
  {
    id: "mission-167",
    order: 167,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "claimDailyRewards",
      target: 10,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "133500000" }],
  },
  {
    id: "mission-168",
    order: 168,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "activatePowerUps",
      target: 11,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "134000000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "epic" },
    ],
  },
  {
    id: "mission-169",
    order: 169,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 20,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "134500000" }],
  },
  {
    id: "mission-170",
    order: 170,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "1.3e12",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "135000000" }],
  },
  {
    id: "mission-171",
    order: 171,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 40,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "135500000" }],
  },
  {
    id: "mission-172",
    order: 172,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "1.5e12",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "136000000" }],
  },
  {
    id: "mission-173",
    order: 173,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "1.5e12",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "136500000" }],
  },
  {
    id: "mission-174",
    order: 174,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "completeCycles",
      target: 416,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "137000000" }],
  },
  {
    id: "mission-175",
    order: 175,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 28,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "137500000" },
      { type: "renown", percent: 2.5 },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "epic" },
    ],
  },
  {
    id: "mission-176",
    order: 176,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "spendGold",
      target: "1.5e12",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "138000000" }],
  },
  {
    id: "mission-177",
    order: 177,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "claimDailyRewards",
      target: 10,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "138500000" }],
  },
  {
    id: "mission-178",
    order: 178,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "activatePowerUps",
      target: 12,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "139000000" }],
  },
  {
    id: "mission-179",
    order: 179,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 21,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "139500000" }],
  },
  {
    id: "mission-180",
    order: 180,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "1.5e12",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "140000000" }],
  },
  {
    id: "mission-181",
    order: 181,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 42,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "140500000" }],
  },
  {
    id: "mission-182",
    order: 182,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "1.5e12",
      scope: "sinceActive",
    },
    rewards: [
      { type: "gold", amount: "141000000" },
      { type: "powerUp", powerUpId: "yggdrasilTear", tier: "epic" },
    ],
  },
  {
    id: "mission-183",
    order: 183,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "1.5e12",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "141500000" }],
  },
  {
    id: "mission-184",
    order: 184,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "completeCycles",
      target: 428,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "142000000" }],
  },
  {
    id: "mission-185",
    order: 185,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 30,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "142500000" }],
  },
  {
    id: "mission-186",
    order: 186,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "spendGold",
      target: "1.5e12",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "143000000" }],
  },
  {
    id: "mission-187",
    order: 187,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "claimDailyRewards",
      target: 10,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "143500000" }],
  },
  {
    id: "mission-188",
    order: 188,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "activatePowerUps",
      target: 12,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "144000000" }],
  },
  {
    id: "mission-189",
    order: 189,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "crossbow",
      target: 22,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "144500000" },
      { type: "powerUp", powerUpId: "mimirCoin", tier: "epic" },
    ],
  },
  {
    id: "mission-190",
    order: 190,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "1.5e12",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "145000000" }],
  },
  {
    id: "mission-191",
    order: 191,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 44,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "145500000" }],
  },
  {
    id: "mission-192",
    order: 192,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "1.5e12",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "146000000" }],
  },
  {
    id: "mission-193",
    order: 193,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "holdGold",
      target: "1.5e12",
      scope: "run",
    },
    rewards: [{ type: "gold", amount: "146500000" }],
  },
  {
    id: "mission-194",
    order: 194,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "completeCycles",
      target: 440,
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "147000000" }],
  },
  {
    id: "mission-195",
    order: 195,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "longship",
      target: 32,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "147500000" }],
  },
  {
    id: "mission-196",
    order: 196,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "spendGold",
      target: "1.5e12",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "148000000" }],
  },
  {
    id: "mission-197",
    order: 197,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "claimDailyRewards",
      target: 10,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "148500000" }],
  },
  {
    id: "mission-198",
    order: 198,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "activatePowerUps",
      target: 12,
      scope: "lifetime",
    },
    rewards: [{ type: "gold", amount: "149000000" }],
  },
  {
    id: "mission-199",
    order: 199,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "earnGold",
      target: "1.5e12",
      scope: "sinceActive",
    },
    rewards: [{ type: "gold", amount: "149500000" }],
  },
  {
    id: "mission-200",
    order: 200,
    requires: { minFactoryUnlocked: "reliquary" },
    objective: {
      type: "ownUnits",
      factory: "reliquary",
      target: 50,
      scope: "lifetime",
    },
    rewards: [
      { type: "gold", amount: "150000000" },
      { type: "renown", percent: 3 },
    ],
  },
] as const satisfies readonly MissionDefinition[];
